spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springMicorService/spring-cloud-config-repository
          username: ******
          password: ******
          search-paths: commonConfig
      label: master
server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka.shop.com
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8001/eureka/


