spring:
  application:
    name: config-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springMicorService/spring-cloud-config-repository
          username: 2274420416@qq.com
          password: xgj@123
server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8001/eureka/


