spring:
  application:
    name: spring_eureka
  security:
    user:
      name: admin
      password: admin
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
       sampler:
         #  默认值为0.1f，现在为了测试设置100%采集
         percentage: 1
server:
  port: 8001
eureka:
  instance:
    hostname: eureka.shop.com
    appname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护


